site_name: LS Docs
site_author: TuneWar
site_url: https://docs.tunewar.de
repo_url: https://github.com/TuneWar/ls-docs

theme:
  name: material
  palette: 
    scheme: slate
    primary: green
  features:
    - navigation.tabs
    - content.code.copy
    - navigation.path
    - navigation.indexes
  language: de

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - search
